### ISSUE TITLE
improve css

### ISSUE THREAD

**Issue by Max-OSSoftware** [zapboy216/react-calculator#1]
make a better UI for our experiment calculator

**Comment by loureed100** [comment]
looks good the way it is

**Comment by amatbruno** [comment]
Hey, you could join the about section with a gray background, with the bottom of the page and center the calculator vertically and horizontally. Try putting a height: 100vh in the body tag so that it picks up the viewport of the screen automatically and it should work, since, from what I see, you already have the calculator centered correctly. 

Regards.
